version: "3.9"
services:
  flcodebase:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./area:/mud/area 
      - ./bounty:/mud/bounty  
      - ./challenge:/mud/challenge  
      - ./clans:/mud/clans 
      - ./gods:/mud/gods 
      - ./log:/mud/log  
      - ./logs:/mud/logs 
      - ./mobprogs:/mud/mobprogs  
      - ./player:/mud/player  
      - ./public_html:/mud/public_html
      - ./savemud:/mud/savemud
    ports:
      - 1848:1848
  web:
    image: nginx:latest
    volumes:
      - ./public_html:/usr/share/nginx/html/
    ports:
      - 80:80
